
# Start up SAMWeb, Nginx, SAM Station, and Apache
#

version: "3.7"
services:

    # Web server/reverse proxy/SSL termination
    apache:
        image: bjwhitefnal/sam_httpd_server 
        ports:
            - "127.0.0.1:8483:8483"
            - "127.0.0.1:8480:8480"
        depends_on:
            - samweb_server
        volumes:
            - osg-ca-volume:/etc/grid-security/certificates


    # SAM Web Server with DB password as a secret
    samweb_server:
        image: bjwhitefnal/samweb_server
        environment:
            - EXPERIMENT=sam_bjwhite
        volumes:
            - type: bind
              source: ./samweb_server/sam-web 
              target: /opt/sam/samweb_server/sam-web
        secrets:
            - samweb_db_secret


    # Service to handle OSG CA Certificates by updating them and making them available via the named volume 'osg-ca-volume'
    osg_authentication:
        image: bjwhitefnal/osg_authentication
        volumes:
            - osg-ca-volume:/etc/grid-security/certificates
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        privileged: true
    
volumes:
    osg-ca-volume:
    
secrets:
    samweb_db_secret:
        file: ./samweb_server/config/secret/postgres.secret
