apiVersion: v1
kind: Service
metadata:
  name: sam-httpd-server-service
  labels:
    app: sam-httpd-server
spec:
  selector:
    app: sam-httpd-server
  ports:
  - name: http
    port: 8480
    targetPort: 8480
  - name: https
    port: 8483
    targetPort: 8483
  externalIPs: [ 131.225.218.183 ]