
-   node: cern.ch
    locations: [ cern-eos, dcache, enstore, samdev ]
    schemas: [ gsiftp, root, srm]
-   node: .
    locations: [ dcache, enstore, samdev ]
    schemas: [ gsiftp, root, srm, file ]
